# Generated by Django 3.2.25 on 2025-02-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_login_db_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_db',
            name='email',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
