# Generated by Django 3.2.25 on 2025-02-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_registration_db_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_db',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
