# Generated by Django 3.2.25 on 2025-02-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_registration_db_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_db',
            name='action',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration_db',
            name='action',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
