# Generated by Django 3.2.25 on 2025-02-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_db',
            name='idno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
