# Generated by Django 3.2.25 on 2025-02-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_db_idno'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField()),
                ('customername', models.CharField(max_length=255)),
                ('customermail', models.CharField(max_length=255)),
                ('productname', models.CharField(max_length=255)),
                ('productcategory', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentstatus', models.IntegerField()),
                ('deliverstatus', models.IntegerField()),
            ],
        ),
    ]
