# Generated by Django 3.2.25 on 2025-02-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_order_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_db',
            name='totalprice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_db',
            name='price',
            field=models.IntegerField(),
        ),
    ]
