# Generated by Django 3.2.25 on 2025-02-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_db',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
