# Generated by Django 3.2.25 on 2025-02-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_db_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_db',
            name='proid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
