name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t my-django-app .

      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 --name my-django-container my-django-app

      - name: Wait for the server to start
        run: |
          sleep 10  # Wait for the server to start

      - name: Run tests
        run: |
          docker exec my-django-container python manage.py test

      - name: Stop and remove the container
        run: |
          docker stop my-django-container
          docker rm my-django-container
